openapi: 3.0.3
info:
  title: Prinzimaker's Link Shortener API
  description: API for creating, managing, and viewing statistics of shortened links.
  version: 1.2.1
  contact:
    name: Aldo Prinzi
    email: aldo@prinzi.it
servers:
  - url: https://api.yoursite.com
    description: Production API
  - url: http://localhost
    description: Development API

paths:
  /api/shorten:
    get:
      summary: Shorten a link
      description: Allows creating a shortened link.
      parameters:
        - name: key
          in: query
          description: API key for authentication (currently any value is valid).
          required: true
          schema:
            type: string
        - name: uri
          in: query
          description: Long URL to be shortened.
          required: true
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: Successfully created a shortened link.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortenLinkResponse'
        '400':
          description: Bad request or missing parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/info:
    get:
      summary: Get short link info
      description: Retrieve information of a shortened link.
      parameters:
        - name: key
          in: query
          description: API key for authentication (currently any value is valid).
          required: true
          schema:
            type: string
        - name: short_id
          in: query
          description: The code of the short link.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved link information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortLinkInfoResponse'
        '400':
          description: Bad request or missing parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/calls:
    get:
      summary: Get short link call log
      description: Retrieve the call log for a shortened link.
      parameters:
        - name: key
          in: query
          description: API key for authentication (currently any value is valid).
          required: true
          schema:
            type: string
        - name: short_id
          in: query
          description: The code of the short link.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved call logs for the shortened link.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortLinkCallsResponse'
        '400':
          description: Bad request or missing parameters.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ShortenLinkResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        original_url:
          type: string
          format: uri
          example: "https://www.example.com/page.php?param=1"
        short_url:
          type: string
          format: uri
          example: "https://yoursite.com/abc123"

    ShortLinkInfoResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        original_url:
          type: string
          format: uri
          example: "https://www.example.com/page.php?param=1"
        created:
          type: string
          format: date-time
          example: "2024-06-15T12:34:56"
        calls_count:
          type: integer
          example: 42

    ShortLinkCallsResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        short_id:
          type: string
          example: "abc123"
        calls_log:
          type: array
          items:
            type: string
          example:
            - "10.10.10.10,2024-06-15 09:50:00,Rome|Lazio|Italy"
            - "128.1.15.16,2024-06-16 11:25:07,Venice|Veneto|Italy"

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: error
        message:
          type: string
          example: "Mandatory parameters missing."
